<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title><?=$this->get_title()?></title>
<link rel="stylesheet" rev="stylesheet" href="<?=$this->build_css_url()?>" type="text/css" />

</head>
<body>
<div class="container">
I'm container
<?php new Web_HeaderPlugin(); ?>
<?php
$this->build_content();
?>
</div>
<script type="text/javascript" src="<?=$this->build_js_url()?>"></script>
</body>
</html>